language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq --no-install-recommends devscripts libwww-perl
    - uscan --force-download
    - sudo apt-get purge -qq libwww-perl
    - sudo apt-get autoremove -qq
    - sudo apt-get purge -qq libhtml-parser-perl libhtml-tagset-perl
    - sudo apt-get install -qq --no-install-recommends debhelper devscripts apache2-dev autotools-dev

script:
    - debuild -uc -us

#notifications:
#  email: false
